export const types = {
  TOGGLE_CART: 'TOGGLE_CART',
  INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  CHECKOUT: 'CHECKOUT',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  LOAD_ORDER_HISTORY: 'LOAD_ORDER_HISTORY',
  LOAD_ORDER_HISTORY_SUCCESS: 'LOAD_ORDER_HISTORY_SUCCESS',
}
