backend:
  name: git-gateway
  branch: master # Branch to update

media_folder: 'static/img' # Media files will be stored in the repo under static/img
public_folder: '/img' # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post-page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
